# Use Node.js LTS as the base image
FROM node:20

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and yarn.lock
COPY ./backend/package.json ./backend/yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the entire project
COPY ./backend .

# Build the project
RUN yarn build

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["yarn", "start:prod"]