# Use Node.js LTS as the base image
FROM node:20

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY ./frontend/package.json ./frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire project
COPY ./frontend .

# Expose the application port
EXPOSE 5173

# Start the application
CMD ["npm", "run", "dev", "--", "--host"]
